import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { buildWitanInputFromRepo } from '../repo-signals.js';

function makeTmpRepo(): string {
  const dir = mkdtempSync(join(tmpdir(), 'witan-signals-'));
  execFileSync('git', ['init', '--quiet'], { cwd: dir });
  execFileSync('git', ['config', 'user.email', 'test@test.com'], { cwd: dir });
  execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
  return dir;
}

function writeFile(dir: string, rel: string, content: string): void {
  const full = join(dir, rel);
  mkdirSync(join(dir, rel.split('/').slice(0, -1).join('/')), { recursive: true });
  writeFileSync(full, content, 'utf8');
  execFileSync('git', ['add', rel], { cwd: dir });
}

function signalFor(dir: string, id: string) {
  const input = buildWitanInputFromRepo({
    productSlug: 'test',
    productDisplayName: 'Test',
    repoPath: dir,
    generatedAt: '2026-06-26T00:00:00.000Z',
  });
  return (input.signals ?? []).find((s) => s.criterionId === id) ?? null;
}

// ─── A4: Python (requirements.txt + pyproject.toml) ────────────────────────
// These parser-focused fixtures carry an explicit deploy marker (Procfile /
// docker-compose.yaml) so they classify as app/service and keep exercising the
// app-norm metrics (pinned_dependency_ratio, required lockfile) after the
// library-vs-app archetype split (goal_cejel_rubric_calibration_archetype_2026-07-10).
// Library-norm behavior is covered in rubric-calibration-archetype.test.ts.

describe('A4 — Python requirements.txt produces real dependency metrics', () => {
  it('reads deps from requirements.txt and credits lockfile when poetry.lock is present', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'Procfile', 'web: gunicorn app:app\n');
    writeFile(
      dir,
      'requirements.txt',
      [
        'requests==2.31.0',
        'httpx>=0.24.0',
        'flask==3.0.0',
        '# comment line',
        '',
        'numpy>=1.24',
      ].join('\n'),
    );
    writeFile(dir, 'poetry.lock', '# generated by Poetry\n[[package]]\nname = "requests"\n');

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();

    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    expect(pinnedRatio?.value).toBeGreaterThan(0); // requests==2.31.0 and flask==3.0.0 are pinned

    const lockfileCoverage = a4?.metrics?.find((m) => m.name === 'lockfile_coverage');
    expect(lockfileCoverage?.value).toBe(1);
  });

  it('reads deps from pyproject.toml [project] and [tool.poetry.dependencies]', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'Procfile', 'web: uvicorn app:app\n');
    writeFile(
      dir,
      'pyproject.toml',
      [
        '[project]',
        'name = "myapp"',
        'dependencies = [',
        '  "requests>=2.28",',
        '  "httpx==0.24.1",',
        '  "pydantic>=2.0",',
        ']',
        '',
        '[tool.poetry.dependencies]',
        'python = "^3.11"',
        'fastapi = "^0.100.0"',
        'uvicorn = "0.23.2"',
      ].join('\n'),
    );
    writeFile(dir, 'uv.lock', '# generated by uv\n');

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();

    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    // httpx==0.24.1 and uvicorn=0.23.2 are pinned; requests/httpx/pydantic/fastapi are ranges
    expect(pinnedRatio?.value).toBeGreaterThan(0);
    expect(pinnedRatio?.max).toBeGreaterThan(3); // at least 4 deps declared
  });
});

// ─── A4: C++ (vcpkg.json) ──────────────────────────────────────────────────

describe('A4 — vcpkg.json produces real dependency metrics', () => {
  it('reads vcpkg.json deps and credits baseline-pinned packages', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'docker-compose.yaml', 'services:\n  app:\n    build: .\n');
    writeFile(
      dir,
      'vcpkg.json',
      JSON.stringify({
        name: 'myapp',
        'builtin-baseline': 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0',
        dependencies: [
          'boost-filesystem',
          'fmt',
          'spdlog',
          { name: 'zlib', 'version>=': '1.2.11' },
          { name: 'openssl' },
        ],
      }),
    );
    writeFile(dir, 'CMakeLists.txt', 'cmake_minimum_required(VERSION 3.20)\nproject(myapp)\n');

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();

    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    // boost-filesystem, fmt, spdlog, openssl → 'baseline' → pinned (4)
    // zlib has "version>=": "1.2.11" → extracted version is "1.2.11" → also pinned (5 total)
    expect(pinnedRatio?.value).toBe(5);
    expect(pinnedRatio?.max).toBe(5);

    // A4 must not be "unverified": there is evidence
    expect((a4?.positiveEvidence ?? []).length).toBeGreaterThan(0);
  });
});

// ─── A4: C++ (CMake FetchContent + find_package) ──────────────────────────

describe('A4 — CMakeLists.txt find_package/FetchContent produces real dependency metrics', () => {
  it('reads find_package and FetchContent_Declare from CMakeLists.txt', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'docker-compose.yaml', 'services:\n  app:\n    build: .\n');
    writeFile(
      dir,
      'CMakeLists.txt',
      [
        'cmake_minimum_required(VERSION 3.20)',
        'project(myapp)',
        'find_package(Boost 1.71 REQUIRED)',
        'find_package(OpenCV 4.0 REQUIRED)',
        'find_package(Threads REQUIRED)',
        'include(FetchContent)',
        'FetchContent_Declare(',
        '  googletest',
        '  GIT_REPOSITORY https://github.com/google/googletest.git',
        '  GIT_TAG v1.14.0',
        ')',
        'FetchContent_Declare(',
        '  nlohmann_json',
        '  GIT_REPOSITORY https://github.com/nlohmann/json.git',
        '  GIT_TAG v3.11.2',
        ')',
      ].join('\n'),
    );

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();

    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    // Boost 1.71 → pinned, OpenCV 4.0 → not a full semver (x.y only passes /^\d+\.\d+/) → pinned
    // Threads → filtered out (cmake-internal), googletest v1.14.0 → pinned, nlohmann_json v3.11.2 → pinned
    // Total: deps parsed = Boost(1.71) + OpenCV(4.0) + googletest(1.14.0) + nlohmann_json(3.11.2) = 4
    // Pinned ones: 1.71 → yes (matches d+.d+), 4.0 → yes, v1.14.0 → yes (stripped to semver), v3.11.2 → yes
    expect(pinnedRatio?.max).toBeGreaterThan(0);
    expect((a4?.positiveEvidence ?? []).length).toBeGreaterThan(0);
  });
});

// ─── A4: C++ (conanfile.txt) ──────────────────────────────────────────────

describe('A4 — conanfile.txt produces real dependency metrics', () => {
  it('reads conan [requires] section and credits lockfile when conan.lock is present', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'docker-compose.yaml', 'services:\n  app:\n    build: .\n');
    writeFile(
      dir,
      'conanfile.txt',
      [
        '[requires]',
        'boost/1.80.0',
        'fmt/8.1.1',
        'spdlog/1.11.0',
        '',
        '[generators]',
        'cmake',
      ].join('\n'),
    );
    writeFile(dir, 'conan.lock', '{"version": "0.5", "profile_host": {}}\n');

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();

    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    expect(pinnedRatio?.value).toBe(3); // all three are exact versions (x.y.z)
    expect(pinnedRatio?.max).toBe(3);

    const lockfileCoverage = a4?.metrics?.find((m) => m.name === 'lockfile_coverage');
    expect(lockfileCoverage?.value).toBe(1);
  });
});

// ─── A4: zero deps is a real (small) signal, not unverified ────────────────

describe('A4 — empty manifest is a real zero signal, not unverified', () => {
  it('a vcpkg.json with zero dependencies still produces metrics', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'docker-compose.yaml', 'services:\n  app:\n    build: .\n');
    writeFile(dir, 'vcpkg.json', JSON.stringify({ name: 'myapp', dependencies: [] }));
    writeFile(dir, 'vcpkg.lock.json', '{"version": 1}\n');

    const a4 = signalFor(dir, 'A4');
    expect(a4).not.toBeNull();
    // lockfile present → lockfile_coverage = 1
    const lockfileCoverage = a4?.metrics?.find((m) => m.name === 'lockfile_coverage');
    expect(lockfileCoverage?.value).toBe(1);
    // 0 deps → pinned_dependency_ratio value=0, max=1 (clamped min)
    const pinnedRatio = a4?.metrics?.find((m) => m.name === 'pinned_dependency_ratio');
    expect(pinnedRatio?.value).toBe(0);
    expect(pinnedRatio?.max).toBe(1);
  });
});

// ─── Monorepo — sub-package inherits root lockfile + CI (no false criticals) ──
// Found 2026-06-30 scoring packages/api: `git ls-files` from a sub-package can't see
// the root pnpm-lock.yaml / .github/workflows, so A4 ("no lockfile") and B3 ("0 CI
// workflows") emitted FALSE CRITICALS. resolveMonorepoContext surfaces ONLY root
// shared-config so those criteria see them; nothing else about the sub-package changes.

describe('Monorepo — sub-package credits root lockfile + CI, no false criticals', () => {
  it('sub-package sees root pnpm-lock.yaml (A4) and root workflows (B3)', () => {
    const root = makeTmpRepo();
    // Deploy marker inside the scanned sub-package: keeps these fixtures on the app-norm
    // A4 path (required lockfile) after the library-vs-app archetype split.
    writeFile(root, 'packages/api/Procfile', 'web: node src/index.js\n');
    writeFile(root, 'pnpm-lock.yaml', 'lockfileVersion: 9.0\n');
    writeFile(
      root,
      '.github/workflows/ci.yml',
      'on:\n  pull_request:\njobs:\n  test:\n    steps:\n      - run: pnpm test\n',
    );
    writeFile(
      root,
      'packages/api/package.json',
      JSON.stringify({ name: 'api', dependencies: { zod: '^3.23.0' } }),
    );
    writeFile(root, 'packages/api/src/index.ts', 'export const x = 1;\n');
    const sub = join(root, 'packages/api');

    const a4 = signalFor(sub, 'A4');
    expect(a4).not.toBeNull();
    // Root lockfile covers the sub-package → coverage 1, no non-reproducible-install critical.
    expect(a4?.metrics?.find((m) => m.name === 'lockfile_coverage')?.value).toBe(1);
    expect((a4?.findings ?? []).some((f) => f.severity === 'critical')).toBe(false);

    const b3 = signalFor(sub, 'B3');
    expect(b3).not.toBeNull();
    // Root PR-gate workflow is counted for the sub-package.
    expect(b3?.metrics?.find((m) => m.name === 'default_branch_ci_depth')?.value).toBeGreaterThan(
      0,
    );
  });

  it('does NOT fabricate: sub-package with NO root lockfile stays A4-critical', () => {
    const root = makeTmpRepo();
    writeFile(root, 'packages/api/Procfile', 'web: node src/index.js\n');
    // No lockfile anywhere in the monorepo.
    writeFile(
      root,
      'packages/api/package.json',
      JSON.stringify({ name: 'api', dependencies: { zod: '^3.23.0' } }),
    );
    writeFile(root, 'packages/api/src/index.ts', 'export const x = 1;\n');
    const sub = join(root, 'packages/api');

    const a4 = signalFor(sub, 'A4');
    expect(a4).not.toBeNull();
    expect(a4?.metrics?.find((m) => m.name === 'lockfile_coverage')?.value).toBe(0);
    expect((a4?.findings ?? []).some((f) => f.severity === 'critical')).toBe(true);
  });

  it('root scan is unchanged: scanning the git root borrows nothing (mono is a no-op)', () => {
    const root = makeTmpRepo();
    writeFile(root, 'Procfile', 'web: node src/index.js\n');
    writeFile(
      root,
      'package.json',
      JSON.stringify({ name: 'root', dependencies: { zod: '^3.23.0' } }),
    );
    writeFile(root, 'src/index.ts', 'export const x = 1;\n');
    // Root has a manifest but no lockfile → the honest result is still A4-critical,
    // exactly as before the monorepo change (resolveMonorepoContext returns null here).
    const a4 = signalFor(root, 'A4');
    expect(a4?.metrics?.find((m) => m.name === 'lockfile_coverage')?.value).toBe(0);
    expect((a4?.findings ?? []).some((f) => f.severity === 'critical')).toBe(true);
  });
});

// ─── A1: C++ test files in spec/ directory ─────────────────────────────────

describe('A1 — AVA root-level test files are detected', () => {
  it('recognizes the test.js convention instead of reporting a configured runner with no tests', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'package.json',
      JSON.stringify({
        name: 'ava-root-test',
        scripts: { test: 'ava' },
        devDependencies: { ava: '^6.0.0' },
      }),
    );
    writeFile(dir, 'index.js', 'export const slugify = (value) => value.toLowerCase();\n');
    writeFile(
      dir,
      'test.js',
      "import test from 'ava';\nimport {slugify} from './index.js';\ntest('slugifies', t => { t.is(slugify('HELLO'), 'hello'); });\n",
    );

    const a1 = signalFor(dir, 'A1');
    expect(a1).not.toBeNull();
    expect((a1?.positiveEvidence ?? []).some((item) => item.path === 'test.js')).toBe(true);
    expect(
      (a1?.findings ?? []).some(
        (finding) =>
          finding.summary ===
          'A test runner is configured, but no concrete test files were detected.',
      ),
    ).toBe(false);
  });
});

describe('A1 — C++ test files under spec/ directory are detected', () => {
  it('counts .cpp files under spec/ as test files', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'spec/unit/foo_spec.cpp',
      '#include <gtest/gtest.h>\nTEST(Foo, Bar) { EXPECT_EQ(1, 1); }\n',
    );
    writeFile(
      dir,
      'spec/unit/baz_spec.cpp',
      '#include <gtest/gtest.h>\nTEST(Baz, Qux) { EXPECT_TRUE(true); }\n',
    );
    writeFile(dir, 'src/foo.cpp', 'int main() { return 0; }\n');
    writeFile(dir, 'CMakeLists.txt', 'cmake_minimum_required(VERSION 3.20)\nproject(myapp)\n');

    const a1 = signalFor(dir, 'A1');
    expect(a1).not.toBeNull();
    // Both spec/ .cpp files should be counted
    const ratio = a1?.metrics?.find((m) => m.name === 'test_to_source_ratio');
    expect(ratio?.value).toBeGreaterThanOrEqual(2);
  });
});

// ─── A1: Content-based C++ test detection ──────────────────────────────────

describe('A1 — C++ test files detected by content (gtest/catch2 macros)', () => {
  it('counts C++ files with TEST() macros even outside test/ directories', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/widget_test.cpp',
      // Standard naming → already detected; confirm non-hollow check works
      '#include <gtest/gtest.h>\nTEST(Widget, Creates) { EXPECT_NE(nullptr, widget); }\n',
    );
    // This file is NOT in a test dir and has no test_ prefix or _test suffix
    writeFile(
      dir,
      'src/integration_suite.cpp',
      '#include <catch2/catch_all.hpp>\nTEST_CASE("integration", "[integration]") { REQUIRE(1 == 1); }\n',
    );
    writeFile(dir, 'src/main.cpp', 'int main() { return 0; }\n');

    const a1 = signalFor(dir, 'A1');
    expect(a1).not.toBeNull();
    // integration_suite.cpp should be detected via content-based scan
    // (widget_test.cpp is caught by _test.cpp naming)
    const ratio = a1?.metrics?.find((m) => m.name === 'test_to_source_ratio');
    expect(ratio?.value).toBeGreaterThanOrEqual(2);
  });

  it('does NOT over-credit a CMake test-runner-only repo with no test files', () => {
    const dir = makeTmpRepo();
    // Only a CMakeLists.txt with enable_testing() but NO actual test files
    writeFile(
      dir,
      'CMakeLists.txt',
      'cmake_minimum_required(VERSION 3.20)\nproject(myapp)\nenable_testing()\nctest_add_tests()\n',
    );
    writeFile(dir, 'src/main.cpp', 'int main() { return 0; }\n');
    writeFile(dir, 'src/lib.cpp', 'void foo() {}\n');

    const a1 = signalFor(dir, 'A1');
    if (a1 === null) return; // no test signal is also valid — runner with no files
    const ratio = a1?.metrics?.find((m) => m.name === 'test_to_source_ratio');
    // test count should be 0; CMakeLists.txt runner does not count as a test file
    expect(ratio?.value).toBe(0);
  });
});

// ─── A1: Header exclusion from denominator ─────────────────────────────────

describe('A1 — C++ headers excluded from source denominator', () => {
  it('does not count .h and .hpp files as source implementation units', () => {
    const dir = makeTmpRepo();
    // 1 test file, 2 .cpp sources, and 5 .h headers
    writeFile(
      dir,
      'tests/test_widget.cpp',
      '#include <gtest/gtest.h>\nTEST(W, A) { EXPECT_EQ(1, 1); }\n',
    );
    writeFile(dir, 'src/widget.cpp', 'void widget() {}\n');
    writeFile(dir, 'src/util.cpp', 'void util() {}\n');
    writeFile(dir, 'include/widget.h', '#pragma once\nvoid widget();\n');
    writeFile(dir, 'include/util.h', '#pragma once\nvoid util();\n');
    writeFile(dir, 'include/types.h', '#pragma once\nstruct Foo {};\n');
    writeFile(dir, 'include/config.h', '#pragma once\n#define VERSION 1\n');
    writeFile(dir, 'include/api.hpp', '#pragma once\nclass Api {};\n');

    const a1 = signalFor(dir, 'A1');
    expect(a1).not.toBeNull();
    const ratio = a1?.metrics?.find((m) => m.name === 'test_to_source_ratio');
    // 1 test file / 2 source .cpp files = 0.5; NOT 1/(2+5) ≈ 0.14
    expect(ratio?.value).toBe(1);
    expect(ratio?.max).toBe(2);
  });
});

// ─── A1: Anti-overfit — genuinely light-on-tests repo stays low ────────────

describe('A1 — anti-overfit: large codebase with few tests stays low', () => {
  it('many source files and one test file keeps the ratio low', () => {
    const dir = makeTmpRepo();
    // 1 test, 20 source files → ratio should be 1/20 = 0.05
    writeFile(
      dir,
      'tests/only_test.cpp',
      '#include <gtest/gtest.h>\nTEST(Only, One) { EXPECT_TRUE(true); }\n',
    );
    for (let i = 0; i < 20; i++) {
      writeFile(dir, `src/module_${i}.cpp`, `void mod${i}() {}\n`);
    }

    const a1 = signalFor(dir, 'A1');
    expect(a1).not.toBeNull();
    const ratio = a1?.metrics?.find((m) => m.name === 'test_to_source_ratio');
    // 1 test / 20 source = 0.05 — should NOT be inflated
    expect(ratio?.value).toBe(1);
    expect(ratio?.max).toBe(20);
  });
});

// ─── A2: FIX 1 — bare env reads do NOT produce 0.0-unverified, they produce N/A ──

describe('A2 — FIX 1: bare env reads → not_applicable, not 0.0-unverified', () => {
  it('JS repo with only process.env reads → A2 not_applicable', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const port = process.env.PORT || 3000;\n');
    writeFile(dir, 'package.json', JSON.stringify({ name: 'mylib', version: '1.0.0' }));

    const a2 = signalFor(dir, 'A2');
    // A bare env read is not a ratable surface. A2 must be not_applicable, never unverified.
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBe(true);
  });

  it('Rust repo with only std::env:: reads → A2 not_applicable', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/main.rs',
      'fn main() { let port = std::env::var("PORT").unwrap_or("8080".into()); }\n',
    );
    writeFile(dir, 'Cargo.toml', '[package]\nname = "mybin"\nversion = "0.1.0"\n');
    writeFile(dir, 'Cargo.lock', '# generated by cargo\n');

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBe(true);
  });

  it('Python repo with only os.environ reads → A2 not_applicable', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/app.py', 'import os\nport = os.environ.get("PORT", "8000")\n');

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBe(true);
  });
});

// ─── A2: FIX 2 — a repo with a ratable surface is always scored, never 0.0-unverified ──

describe('A2 — FIX 2: ratable surface → always scored, floor >= honest value', () => {
  it('.env.example present + clean → A2 is scored, not null/unverified', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    writeFile(dir, '.env.example', 'API_KEY=your-api-key-here\nPORT=3000\n');
    writeFile(
      dir,
      '.gitignore',
      '# env\n.env\n.env.local\n.env.production\nnode_modules/\ndist/\n',
    );

    const a2 = signalFor(dir, 'A2');
    // Ratable surface (.env.example + .gitignore .env rule). Must be scored, not null.
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBeFalsy();
    // secret_cleanliness must be present (repo is secret-clean)
    const cleanliness = a2?.metrics?.find((m) => m.name === 'secret_cleanliness');
    expect(cleanliness).toBeDefined();
    expect(cleanliness?.value).toBe(1);
    // Evidence must be non-empty so scorer fires at honest floor
    expect((a2?.positiveEvidence ?? []).length).toBeGreaterThan(0);
  });

  it('data-layer-only repo (migrations, no .env files) → scored, not null/unverified', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'migrations/0001_init.sql',
      'CREATE TABLE users (id SERIAL PRIMARY KEY, email TEXT);\n',
    );
    writeFile(dir, 'src/db.py', 'import psycopg2\nconn = psycopg2.connect(os.environ["DB_URL"])\n');

    const a2 = signalFor(dir, 'A2');
    // Data layer present. Must be scored, not null/unverified.
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBeFalsy();
    const cleanliness = a2?.metrics?.find((m) => m.name === 'secret_cleanliness');
    expect(cleanliness).toBeDefined();
    expect((a2?.positiveEvidence ?? []).length).toBeGreaterThan(0);
  });
});

// ─── A2: ANTI-OVERFIT — committed secret stays LOW/critical, not N/A ──────────

describe('A2 — anti-overfit: committed .env with secret → LOW/critical, not N/A', () => {
  it('committed .env.production with secret-shaped value → A2 is critical finding, not N/A', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    // 40+ alphanumeric chars matches SECRET_VALUE_PATTERN [A-Za-z0-9/+_-]{40,}.
    // Using .env.production (not .env) to avoid any global-gitignore false negatives.
    writeFile(
      dir,
      '.env.production',
      'SESSION_SECRET=m9Qx7Lp2Zr8Tv5Nc3Bq6Hn4Jk1Sd0Fg9We8Rt7Yu6Io5Pa\nPORT=3000\n',
    );

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    expect(a2?.notApplicable).toBeFalsy();
    const hasCritical = (a2?.findings ?? []).some((f) => f.severity === 'critical');
    expect(hasCritical).toBe(true);
  });
});

// ─── A2: prefixed filler-run token is a placeholder, not a committed secret ────
// Found 2026-06-30 running Witan on the QuantDinger competitor repo: a doc
// placeholder `TOKEN=qd_agent_xxxx…` was scored as a committed secret because the
// old placeholder pattern only matched values that were ENTIRELY filler (^x{3,}$).

describe('A2 — prefixed filler-run token (qd_agent_xxxx…) is a placeholder', () => {
  it('doc placeholder with a real prefix + filler run → NO committed-secret critical', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    writeFile(
      dir,
      'docs/AGENT_QUICKSTART.md',
      '## Auth\n\n```\nTOKEN=qd_agent_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n```\n',
    );

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const hasCritical = (a2?.findings ?? []).some((f) => f.severity === 'critical');
    expect(hasCritical).toBe(false);
  });

  it('does NOT suppress a genuine high-entropy committed secret (no false-negative)', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    writeFile(
      dir,
      '.env.production',
      'SESSION_SECRET=m9Qx7Lp2Zr8Tv5Nc3Bq6Hn4Jk1Sd0Fg9We8Rt7Yu6Io5Pa\nPORT=3000\n',
    );

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const hasCritical = (a2?.findings ?? []).some((f) => f.severity === 'critical');
    expect(hasCritical).toBe(true);
  });
});

// ─── A2: test-path downgrade (goal_cejel_test_path_downgrade_2026-07-06) ──────
// Dogfooding cejel on its own repo flagged a fake secret embedded in a test fixture
// (calibration-fixtures.ts, used to TEST that A2 fires) as a critical committed-secret
// leak — cejel cried wolf on its own test data. Same secret shape must downgrade to
// info in a test/fixture path but stay critical in a production src path.

describe('A2 — test-path downgrade: same secret, test/fixture path vs src path', () => {
  it('secret-shaped value inside a __tests__/fixtures file → downgraded to info, not critical', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    writeFile(
      dir,
      'src/__tests__/fixtures/calibration-fixtures.ts',
      'export const FAKE_API_KEY = "m9Qx7Lp2Zr8Tv5Nc3Bq6Hn4Jk1Sd0Fg9We8Rt7Yu6Io5Pa";\n',
    );

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const secretFinding = (a2?.findings ?? []).find((f) => f.summary.includes('Secret-shaped'));
    expect(secretFinding?.severity).toBe('info');
    expect(secretFinding?.summary).toContain('test/fixture file');
    expect(a2?.metrics?.find((m) => m.name === 'secret_cleanliness')?.value).toBe(1);
  });

  it('same secret-shaped value committed in a production src file → stays critical', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'const x = process.env.API_KEY;\n');
    writeFile(
      dir,
      'src/config/api-key.ts',
      'export const FAKE_API_KEY = "m9Qx7Lp2Zr8Tv5Nc3Bq6Hn4Jk1Sd0Fg9We8Rt7Yu6Io5Pa";\n',
    );

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const hasCritical = (a2?.findings ?? []).some((f) => f.severity === 'critical');
    expect(hasCritical).toBe(true);
    expect(a2?.metrics?.find((m) => m.name === 'secret_cleanliness')?.value).toBe(0);
  });
});

// ─── B4: generic audit-trail hygiene scores on EXTERNAL code (not blanket N/A) ──
// Found 2026-06-30 (QuantDinger run): B4's collector is generic (CHANGELOG/SECURITY/
// AUDIT/STATUS + docs runbooks), but a substrate gate blanket-N/A'd it on external
// repos. Un-gated: it scores when audit artifacts exist; B1/B5 stay substrate-N/A.

describe('B4 — audit-trail half scores on external (non-substrate) code', () => {
  it('external repo with CHANGELOG.md → B4 scored (not N/A); B1/B5 stay N/A', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'export const x = 1;\n');
    writeFile(dir, 'CHANGELOG.md', '# Changelog\n\n## 1.0.0 - 2026-01-15\n\nInitial release.\n');

    const b4 = signalFor(dir, 'B4');
    expect(b4).not.toBeNull();
    expect(b4?.notApplicable).toBeFalsy();
    const depth = b4?.metrics?.find((m) => m.name === 'audit_artifact_depth');
    expect(depth?.value).toBeGreaterThan(0);

    // B1 and B5 remain substrate-specific N/A on external code.
    expect(signalFor(dir, 'B1')?.notApplicable).toBe(true);
    expect(signalFor(dir, 'B5')?.notApplicable).toBe(true);
  });

  it('external repo with NO audit artifacts → B4 is explicit not_applicable (excluded from average, not scored 0)', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'export const x = 1;\n');

    const b4 = signalFor(dir, 'B4');
    // goal_cejel_calibration_fix_with_strict_gate_2026-07-06: a `null` signal here scores
    // 0.0-unverified and IS included in the process-trust average (only status
    // 'not_applicable' is excluded — see averageScore in scoring.ts). A repo with zero
    // recognized audit-trail artifacts must return an explicit not_applicable signal instead.
    expect(b4).not.toBeNull();
    expect(b4?.notApplicable).toBe(true);
  });

  // ─── goal_cejel_b4_archetype_gate_2026-07-11: archetype-aware N/A gate ────────────
  // B4 was scoring a false CRITICAL on repos whose ONLY audit-trail artifact is a static
  // security policy (SECURITY.md) — e.g. ossf/scorecard, which publishes release notes via
  // GitHub Releases rather than a committed CHANGELOG. A lone security policy is not a
  // ratable audit-trail surface (it has no expectation of "freshness"); this must be
  // excluded, never scored punitively.

  it('Guard 1 (LOAD-BEARING) — repo with ONLY a SECURITY.md and no other audit-trail artifact → B4 is not_applicable, never a punitive score', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'export const x = 1;\n');
    writeFile(dir, 'SECURITY.md', '# Security Policy\n\nReport issues to security@example.com.\n');

    const b4 = signalFor(dir, 'B4');
    expect(b4).not.toBeNull();
    // Revert this gate (score SECURITY.md-only as a ratable surface again) → RED: this repo
    // would receive the exact false CRITICAL the goal was written to kill (1 file / cap 3,
    // 0/1 freshness ratio).
    expect(b4?.notApplicable).toBe(true);
    expect(b4?.notes).toMatch(/security-policy|no ratable surface|GitHub Releases/i);
  });

  it('Guard 2 (LOAD-BEARING) — repo WITH a genuine CHANGELOG and poor/absent freshness is still scored (not softened) even alongside SECURITY.md', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'export const x = 1;\n');
    writeFile(dir, 'SECURITY.md', '# Security Policy\n\nReport issues to security@example.com.\n');
    // A genuinely stale changelog: no freshness marker (no run-year/recent/latest/current).
    writeFile(dir, 'CHANGELOG.md', '# Changelog\n\n## 0.1.0 - 2019-02-01\n\nFirst cut.\n');

    const b4 = signalFor(dir, 'B4');
    expect(b4).not.toBeNull();
    // Revert (blanket-softening B4 whenever SECURITY.md is present) → RED: a genuinely stale
    // audit trail must still be penalised exactly as before this goal.
    expect(b4?.notApplicable).toBeFalsy();
    const freshness = b4?.metrics?.find((m) => m.name === 'audit_freshness_depth');
    expect(freshness?.value).toBe(0);
  });
});

// ─── B6: privileged-operation human gating (goal_privileged_op_human_gate_learn_2026-07-04) ──

describe('B6 — privileged-operation human gating', () => {
  it('repo with no privileged-operation surface at all → not_applicable', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.js', 'export const x = 1;\n');

    const b6 = signalFor(dir, 'B6');
    expect(b6?.notApplicable).toBe(true);
  });

  it('documents privileged ops as human-executed and gates role elevation → scores well', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'docs/runbooks/prod-admin.md',
      '# Prod admin\n\nPrivileged operations are human-executed; agents never hold prod admin credentials.\n',
    );
    writeFile(
      dir,
      'src/db/verify-role.ts',
      [
        "import { sql } from 'drizzle-orm';",
        'export async function verifyAsAppRole(tx) {',
        "  const row = await tx.execute(sql`select pg_has_role(current_user, 'app_rls', 'member') as ok`);",
        '  if (!row.ok) throw new Error("not a member");',
        "  await tx.execute(sql.raw('set local role app_rls'));",
        '}',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    expect(b6).not.toBeNull();
    expect(b6?.notApplicable).toBeFalsy();
    expect(b6?.findings ?? []).toHaveLength(0);
    expect(b6?.metrics?.find((m) => m.name === 'human_gate_documented')?.value).toBe(1);
    expect(b6?.metrics?.find((m) => m.name === 'fail_closed_privilege_check')?.value).toBe(1);
    expect(b6?.metrics?.find((m) => m.name === 'privilege_escalation_cleanliness')?.value).toBe(1);
  });

  it('executes a role-membership GRANT in code with no documented human gate → critical finding', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/db/bootstrap.ts',
      [
        "import { sql } from 'drizzle-orm';",
        'export async function bootstrapMigrationRole(db) {',
        "  await db.execute(sql.raw('GRANT app_rls TO migration_role'));",
        '}',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    expect(b6).not.toBeNull();
    expect(b6?.findings).toHaveLength(1);
    expect(b6?.findings?.[0]?.severity).toBe('critical');
    expect(b6?.metrics?.find((m) => m.name === 'privilege_escalation_cleanliness')?.value).toBe(0);
  });

  it('same GRANT statement, but the file also documents the human gate → not flagged as ungated', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/db/bootstrap.ts',
      [
        "import { sql } from 'drizzle-orm';",
        '// This GRANT is a one-time, human-executed, operator-run Postgres privilege',
        '// grant — never agent-run. It is documented here, never executed by this module.',
        "export const MIGRATION_ROLE_GRANT_CHECKLIST = 'GRANT app_rls TO migration_role';",
        'export async function noop(db) {',
        "  await db.execute(sql.raw('select 1'));",
        '}',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    expect(b6).not.toBeNull();
    expect(b6?.findings ?? []).toHaveLength(0);
  });

  it('ordinary object-privilege GRANT (SELECT/USAGE to an app role) is not a self-escalation finding', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/db/provision.ts',
      [
        "import { sql } from 'drizzle-orm';",
        'export async function provisionTable(tx, schema, table) {',
        '  await tx.execute(sql.raw(`grant select, insert, update, delete on ${schema}.${table} to app_rls`));',
        '  await tx.execute(sql.raw(`grant usage on schema ${schema} to app_rls`));',
        '}',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    // Ordinary table/schema object grants to the app role are routine and not
    // an escalation signal — with no other privileged-ops surface, B6 is N/A.
    expect(b6?.notApplicable).toBe(true);
  });
});

// ─── B6: test-path downgrade (goal_cejel_test_path_downgrade_2026-07-06) ──────
// Dogfooding cejel on its own repo flagged a GRANT/role-membership statement inside a
// `.test.ts` (a test asserting that B6's detector fires) as a critical ungated
// privilege escalation — cejel cried wolf on its own test suite. Same GRANT statement
// must downgrade to info in a test/fixture path but stay critical in a production src
// file with no documented human gate.

describe('B6 — test-path downgrade: same GRANT, test/fixture path vs src path', () => {
  it('GRANT statement inside a .test.ts file → downgraded to info, not critical', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/db/bootstrap.test.ts',
      [
        "import { sql } from 'drizzle-orm';",
        "test('bootstrap grants role membership', async () => {",
        "  await db.execute(sql.raw('GRANT app_rls TO migration_role'));",
        '});',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    expect(b6).not.toBeNull();
    expect(b6?.findings).toHaveLength(1);
    expect(b6?.findings?.[0]?.severity).toBe('info');
    expect(b6?.findings?.[0]?.summary).toContain('test/fixture file');
    expect(b6?.metrics?.find((m) => m.name === 'privilege_escalation_cleanliness')?.value).toBe(1);
  });

  it('same GRANT statement in a production src file with no human gate → stays critical', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/db/bootstrap.ts',
      [
        "import { sql } from 'drizzle-orm';",
        'export async function bootstrapMigrationRole(db) {',
        "  await db.execute(sql.raw('GRANT app_rls TO migration_role'));",
        '}',
      ].join('\n'),
    );

    const b6 = signalFor(dir, 'B6');
    expect(b6).not.toBeNull();
    expect(b6?.findings).toHaveLength(1);
    expect(b6?.findings?.[0]?.severity).toBe('critical');
    expect(b6?.metrics?.find((m) => m.name === 'privilege_escalation_cleanliness')?.value).toBe(0);
  });
});

// ─── A2: FIX 3 — env_handling_depth credits Python/Rust/Ruby env reads ────────

describe('A2 — FIX 3: env_handling_depth credits multi-language env reads', () => {
  it('Python repo with .env.example + .gitignore + os.environ → depth 3', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/app.py', 'import os\nport = os.environ.get("PORT", "8000")\n');
    writeFile(dir, '.env.example', 'PORT=8000\nDATABASE_URL=postgresql://localhost/myapp\n');
    writeFile(dir, '.gitignore', '.env\n*.pyc\n__pycache__/\n');
    writeFile(dir, 'migrations/0001_init.sql', 'CREATE TABLE users (id SERIAL PRIMARY KEY);\n');

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const depth = a2?.metrics?.find((m) => m.name === 'env_handling_depth');
    // .env.example (1) + .gitignore .env rule (1) + os.environ read (1) = 3
    expect(depth?.value).toBe(3);
  });

  it('Rust repo with .env.example + std::env:: reads → depth >= 2', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/main.rs', 'fn main() { let port = std::env::var("PORT").unwrap(); }\n');
    writeFile(dir, '.env.example', 'PORT=8080\n');
    writeFile(dir, 'migrations/0001_init.sql', 'CREATE TABLE sessions (id SERIAL PRIMARY KEY);\n');
    writeFile(dir, 'Cargo.toml', '[package]\nname = "myapp"\nversion = "0.1.0"\n');
    writeFile(dir, 'Cargo.lock', '# generated by cargo\n');

    const a2 = signalFor(dir, 'A2');
    expect(a2).not.toBeNull();
    const depth = a2?.metrics?.find((m) => m.name === 'env_handling_depth');
    // .env.example (1) + std::env::var read (1) = 2 (no .gitignore .env rule)
    expect(depth?.value).toBeGreaterThanOrEqual(2);
  });
});

// ─── A3: archetype-aware N/A gate ──────────────────────────────────────────

describe('A3 — library (source + tests, no deploy surface) → not_applicable', () => {
  it('a library with source, tests, and no server entrypoint or deploy config → A3 N/A', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.ts', 'export function add(a: number, b: number) { return a + b; }\n');
    writeFile(
      dir,
      'src/__tests__/index.test.ts',
      "import { add } from '../index.js';\ntest('add', () => expect(add(1,2)).toBe(3));\n",
    );
    writeFile(
      dir,
      'package.json',
      JSON.stringify({ name: 'my-library', version: '1.0.0', scripts: { test: 'vitest' } }),
    );

    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBe(true);
  });
});

describe('A3 — Dockerfile alone (no server entrypoint, no deploy target) → not_applicable', () => {
  it('a repo with only a build Dockerfile → A3 N/A', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.ts', 'export function foo() { return 42; }\n');
    writeFile(dir, 'Dockerfile', 'FROM node:20\nCOPY . .\nRUN npm run build\n');

    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBe(true);
  });
});

describe('A3 — example-entrypoint guard: app.listen only in examples/ → not_applicable', () => {
  it('library with app.listen only under examples/ → A3 N/A (not a service)', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.ts', 'export function createApp() { return {}; }\n');
    writeFile(dir, 'src/middleware.ts', 'export function middleware() {}\n');
    // The only server start is under examples/ — this does NOT make it a service
    writeFile(
      dir,
      'examples/server.js',
      "const { createApp } = require('../src/index.js');\nconst app = createApp();\napp.listen(3000);\n",
    );
    writeFile(dir, 'package.json', JSON.stringify({ name: 'my-framework', version: '1.0.0' }));

    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBe(true);
  });
});

describe('A3 — service scored LOW: server entrypoint but no health/observability/rollback', () => {
  it('a service with app.listen but no health check → A3 is scored, not N/A, and LOW', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/server.js',
      "const express = require('express');\nconst app = express();\napp.listen(3000);\n",
    );
    writeFile(
      dir,
      'package.json',
      JSON.stringify({ name: 'my-service', version: '1.0.0', scripts: { build: 'tsc' } }),
    );

    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBeFalsy();
    // Scored — not N/A. With only a server entrypoint and a build script but
    // no health check, observability, or rollback artifacts, score should be LOW.
    const primitives = a3?.metrics?.find((m) => m.name === 'prod_readiness_primitives');
    expect(primitives).toBeDefined();
    // No deploy config, no health check, no observability, no rollback → very few primitives
    expect((primitives?.value ?? 99) < 4).toBe(true);
  });

  it('a service with uvicorn.run in app.py but no observability → A3 scored, not N/A', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'app.py',
      'from fastapi import FastAPI\nimport uvicorn\napp = FastAPI()\nif __name__ == "__main__":\n    uvicorn.run(app, host="0.0.0.0", port=8000)\n',
    );

    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBeFalsy();
  });
});

describe('A3 — service scores higher with health check + observability + rollback', () => {
  it('service with server + healthcheck + observability + migration-safety scores higher than sloppy service', () => {
    const sloppyDir = makeTmpRepo();
    writeFile(
      sloppyDir,
      'src/server.js',
      "const express = require('express');\nconst app = express();\napp.listen(3000);\n",
    );
    writeFile(
      sloppyDir,
      'package.json',
      JSON.stringify({ name: 'sloppy', version: '1.0.0', scripts: { build: 'tsc' } }),
    );

    const goodDir = makeTmpRepo();
    writeFile(
      goodDir,
      'src/server.js',
      "const express = require('express');\nconst app = express();\napp.get('/health', (req, res) => res.json({ ok: true }));\napp.listen(3000);\n",
    );
    writeFile(goodDir, 'src/health.ts', 'export function healthCheck() { return { ok: true }; }\n');
    writeFile(
      goodDir,
      'src/observability.ts',
      "import * as Sentry from '@sentry/node';\nSentry.init({ dsn: process.env.SENTRY_DSN });\n",
    );
    writeFile(
      goodDir,
      'migrations/0001_init.sql',
      'CREATE TABLE events (id SERIAL PRIMARY KEY);\n',
    );
    writeFile(
      goodDir,
      'docs/rollback.md',
      '# Rollback procedures\nTo roll back: run down migration scripts in reverse order.\n',
    );
    writeFile(
      goodDir,
      '.github/workflows/ci.yml',
      'on:\n  push:\n    branches: [main]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - run: fly deploy\n',
    );
    writeFile(
      goodDir,
      'package.json',
      JSON.stringify({
        name: 'good-service',
        version: '1.0.0',
        scripts: { build: 'tsc', test: 'vitest' },
      }),
    );

    const sloppyA3 = signalFor(sloppyDir, 'A3');
    const goodA3 = signalFor(goodDir, 'A3');

    expect(sloppyA3?.notApplicable).toBeFalsy();
    expect(goodA3?.notApplicable).toBeFalsy();

    // Both are services; the well-equipped one should have more prod_readiness_primitives
    const sloppyPrimitives = sloppyA3?.metrics?.find((m) => m.name === 'prod_readiness_primitives');
    const goodPrimitives = goodA3?.metrics?.find((m) => m.name === 'prod_readiness_primitives');
    expect((goodPrimitives?.value ?? 0) > (sloppyPrimitives?.value ?? 0)).toBe(true);
  });
});

describe('A3 — anti-overfit: service with poor readiness scores LOW, never N/A', () => {
  it('vercel.json present but no health check or observability → A3 scored LOW, not N/A', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'src/index.ts',
      'export default function handler(req: any, res: any) { res.json({ ok: true }); }\n',
    );
    writeFile(dir, 'vercel.json', JSON.stringify({ version: 2 }));
    // No health check, no observability, no rollback artifacts
    const a3 = signalFor(dir, 'A3');
    expect(a3).not.toBeNull();
    expect(a3?.notApplicable).toBeFalsy();
    // The deploy config is detected — it's a service, but readiness is limited
    expect((a3?.positiveEvidence ?? []).length).toBeGreaterThan(0);
  });
});

// Regression coverage for the live crash (2026-07-06, goal_cejel_scan_robustness_ingest_and_bom):
// scoring `vite` threw "Unexpected token '﻿'" because package.json carried a UTF-8
// byte-order mark and JSON.parse rejects that outright. A BOM'd package.json must scan to
// completion, never abort the whole certificate.
describe('robustness — BOM-prefixed package.json does not crash the scan', () => {
  it('scans to completion when package.json starts with a UTF-8 BOM', () => {
    const dir = makeTmpRepo();
    writeFile(
      dir,
      'package.json',
      `﻿${JSON.stringify({
        name: 'bom-repo',
        scripts: { test: 'vitest run', build: 'tsc' },
        dependencies: { zod: '^3.0.0' },
      })}`,
    );
    writeFile(dir, 'pnpm-lock.yaml', 'lockfileVersion: 9.0\n');
    writeFile(dir, 'src/a.test.ts', "it('ok', () => expect(1).toBe(1));\n");

    expect(() =>
      buildWitanInputFromRepo({
        productSlug: 'test',
        productDisplayName: 'Test',
        repoPath: dir,
        generatedAt: '2026-07-06T00:00:00.000Z',
      }),
    ).not.toThrow();

    // The BOM'd package.json's scripts/dependencies must still be read (skip-with-note only
    // applies to a genuinely malformed file, not a valid one wrapped in a BOM). This fixture
    // has no deploy surface, so A4 scores on library norms — the dependency-spec parse
    // surfaces as declared_version_range_ratio (zod ^3.0.0 = 1 constrained spec).
    const a4 = signalFor(dir, 'A4');
    expect(a4?.metrics?.find((m) => m.name === 'declared_version_range_ratio')).toMatchObject({
      value: 1,
      max: 1,
    });
  });
});

describe('filesystem boundary — tracked symlinks are not repository evidence', () => {
  it('does not read or cite a tracked README symlink whose target escapes the checkout', () => {
    const dir = makeTmpRepo();
    const outside = mkdtempSync(join(tmpdir(), 'witan-signals-outside-'));
    writeFileSync(join(outside, 'README.md'), '# Ambient host claim\n', 'utf8');
    symlinkSync(join(outside, 'README.md'), join(dir, 'README.md'));
    execFileSync('git', ['add', 'README.md'], { cwd: dir });
    writeFile(dir, 'src/index.ts', 'export const implementation = true;\n');

    const input = buildWitanInputFromRepo({
      productSlug: 'symlink-boundary',
      productDisplayName: 'Symlink Boundary',
      repoPath: dir,
      generatedAt: '2026-07-18T00:00:00.000Z',
    });
    const evidencePaths = (input.signals ?? []).flatMap((signal) => [
      ...(signal.positiveEvidence ?? []).map((evidence) => evidence.path),
      ...(signal.findings ?? []).map((finding) => finding.evidence.path),
    ]);

    expect(evidencePaths).not.toContain('README.md');
  });

  it('does not treat credential history on an unrelated ref as evidence for HEAD', () => {
    const dir = makeTmpRepo();
    writeFile(dir, 'src/index.ts', 'export const implementation = true;\n');
    execFileSync('git', ['commit', '--quiet', '-m', 'clean head'], { cwd: dir });
    const cleanHead = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: dir,
      encoding: 'utf8',
    }).trim();

    execFileSync('git', ['switch', '--quiet', '-c', 'ambient-history'], { cwd: dir });
    writeFile(dir, '.env.production', 'API_TOKEN=not-a-real-secret-value\n');
    execFileSync('git', ['commit', '--quiet', '-m', 'unrelated credential path'], { cwd: dir });
    execFileSync('git', ['checkout', '--quiet', '--detach', cleanHead], { cwd: dir });

    const a2 = signalFor(dir, 'A2');
    expect(a2?.notApplicable).toBe(true);
    expect(a2?.positiveEvidence ?? []).not.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ label: '.env path detected in git history' }),
      ]),
    );
  });
});

// Guard 3 (goal_cejel_generalize_homefield_rule_and_rescore_protocol_2026-07-12): NO VENDOR
// NAME DEFINES A DIMENSION. The scheduled-product-health-workflow sub-signal (A1) must be
// detected by SHAPE (schedule trigger + test-run command), never by keying off a Barg Labs
// filename or agent name. A static assert over the collector's own source, plus the
// behavioral genericity tests in witan-report.test.ts, is the regression guard.
describe('Guard 3 — no vendor name defines the scheduled-health-workflow dimension', () => {
  it('the A1 collector never gates the scheduled-workflow finding on a literal vendor filename', () => {
    const source = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '../repo-signals.ts'),
      'utf8',
    );
    const collectorStart = source.indexOf('function collectA1TestIntegrityEvidence');
    const collectorEnd = source.indexOf('\nfunction collectA2IsolationEvidence');
    expect(collectorStart).toBeGreaterThan(-1);
    expect(collectorEnd).toBeGreaterThan(collectorStart);
    const collectorSource = source.slice(collectorStart, collectorEnd);

    // No Barg-Labs-specific workflow filename may appear as a quoted literal inside the A1
    // collector body — the collector must reason purely from the workflow's shape (schedule
    // trigger + test-run command), never by comparing repoFiles against a vendor-named path.
    // The public evidence taxonomy uses the generic scheduled_health_summary kind for this
    // signal; do not reintroduce a vendor/agent name in the emitted evidence kind.
    const vendorFilenamePattern = /['"][^'"]*(bede|edgar|aelfric)[^'"]*\.ya?ml['"]/i;
    expect(collectorSource).not.toMatch(vendorFilenamePattern);
  });
});
